package br.edu.unipampa.model;
// Generated 29/07/2015 23:10:49 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente implements java.io.Serializable {

    private int idpaciente;
    private String nome;
    private String sexo;
    private String endereco;
    private String profissao;
    private String escolaridade;
    private String naturalidade;
    private String pessoaContato;
    private String moradia;
    private int idade;
    private String nascimento;
    private String cidade;
    private String estadoCivil;
    private String etnia;
    private String servicoRef;
    private String telefone;
    private String rg;
    private String prontuario;
    private Date dataUltimaConsulta;

    public Paciente() {
    }

    // Informações do paciente, criando o objeto.
    public Paciente(String nome, String sexo, String endereco, String profissao, String escolaridade, String naturalidade, String pessoaContato, String moradia, String nascimento, String cidade, String estadoCivil, String etnia, String servicoRef, String telefone, String rg) {
        this.nome = nome;
        this.sexo = sexo;
        this.endereco = endereco;
        this.profissao = profissao;
        this.escolaridade = escolaridade;
        this.naturalidade = naturalidade;
        this.pessoaContato = pessoaContato;
        this.moradia = moradia;
        //this.idade = idade;
        this.nascimento = nascimento;
        this.cidade = cidade;
        this.estadoCivil = estadoCivil;
        this.etnia = etnia;
        this.servicoRef = servicoRef;
        this.telefone = telefone;
        this.rg = rg;
    }

    /**
     * @return the idpaciente
     */
    public int getIdpaciente() {
        return idpaciente;
    }

    /**
     * @param idpaciente the idpaciente to set
     */
    public void setIdpaciente(int idpaciente) {
        this.idpaciente = idpaciente;
    }

    /**
     * @return the nome
     */
    public String getNome() {
        return nome;
    }

    /**
     * @param nome the nome to set
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * @return the sexo
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * @param sexo the sexo to set
     */
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    /**
     * @return the endereco
     */
    public String getEndereco() {
        return endereco;
    }

    /**
     * @param endereco the endereco to set
     */
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    /**
     * @return the profissao
     */
    public String getProfissao() {
        return profissao;
    }

    /**
     * @param profissao the profissao to set
     */
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    /**
     * @return the escolaridade
     */
    public String getEscolaridade() {
        return escolaridade;
    }

    /**
     * @param escolaridade the escolaridade to set
     */
    public void setEscolaridade(String escolaridade) {
        this.escolaridade = escolaridade;
    }

    /**
     * @return the naturalidade
     */
    public String getNaturalidade() {
        return naturalidade;
    }

    /**
     * @param naturalidade the naturalidade to set
     */
    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }

    /**
     * @return the pessoaContato
     */
    public String getPessoaContato() {
        return pessoaContato;
    }

    /**
     * @param pessoaContato the pessoaContato to set
     */
    public void setPessoaContato(String pessoaContato) {
        this.pessoaContato = pessoaContato;
    }

    /**
     * @return the moradia
     */
    public String getMoradia() {
        return moradia;
    }

    /**
     * @param moradia the moradia to set
     */
    public void setMoradia(String moradia) {
        this.moradia = moradia;
    }

    /**
     * @return the idade
     */
    public int getIdade() {
        return idade;
    }

    /**
     * @param idade the idade to set
     */
    public void setIdade(int idade) {
        this.idade = idade;
    }

    /**
     * @return the nascimento
     */
    public String getNascimento() {
        return nascimento;
    }

    /**
     * @param nascimento the nascimento to set
     */
    public void setNascimento(String nascimento) {
        this.nascimento = nascimento;
    }

    /**
     * @return the cidade
     */
    public String getCidade() {
        return cidade;
    }

    /**
     * @param cidade the cidade to set
     */
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    /**
     * @return the estadoCivil
     */
    public String getEstadoCivil() {
        return estadoCivil;
    }

    /**
     * @param estadoCivil the estadoCivil to set
     */
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    /**
     * @return the etnia
     */
    public String getEtnia() {
        return etnia;
    }

    /**
     * @param etnia the etnia to set
     */
    public void setEtnia(String etnia) {
        this.etnia = etnia;
    }

    /**
     * @return the servicoRef
     */
    public String getServicoRef() {
        return servicoRef;
    }

    /**
     * @param servicoRef the servicoRef to set
     */
    public void setServicoRef(String servicoRef) {
        this.servicoRef = servicoRef;
    }

    /**
     * @return the telefone
     */
    public String getTelefone() {
        return telefone;
    }

    /**
     * @param telefone the telefone to set
     */
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    /**
     * @return the rg
     */
    public String getRg() {
        return rg;
    }

    /**
     * @param rg the rg to set
     */
    public void setRg(String rg) {
        this.rg = rg;
    }

    /**
     * @return the prontuario
     */
    public String getProntuario() {
        return prontuario;
    }

    /**
     * @param prontuario the prontuario to set
     */
    public void setProntuario(String prontuario) {
        this.prontuario = prontuario;
    }

    /**
     * @return the dataUltimaConsulta
     */
    public Date getDataUltimaConsulta() {
        return dataUltimaConsulta;
    }

    /**
     * @param dataUltimaConsulta the dataUltimaConsulta to set
     */
    public void setDataUltimaConsulta(Date dataUltimaConsulta) {
        this.dataUltimaConsulta = dataUltimaConsulta;
    }

}
