package br.edu.unipampa.model;
// Generated 29/07/2015 23:10:49 by Hibernate Tools 4.3.1

import br.edu.unipampa.dao.UsuarioDAO;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private int idusuario;
    private int prontuario;
    private String nomeUsuario;
    private String emailUsuario;
    private String usuario;
    private String senhaUsuario;
    private Boolean administradorUsuario;
    private Boolean ativoUsuario;
    private Set prontuarios = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nomeUsuario, String emailUsuario, String usuario, String senhaUsuario, Boolean administradorUsuario) {
        this.nomeUsuario = nomeUsuario;
        this.emailUsuario = emailUsuario;
        this.usuario = usuario;
        this.senhaUsuario = senhaUsuario;
        this.ativoUsuario = true;
        this.administradorUsuario = administradorUsuario;
    }
    
    public Usuario(int idUser, String nomeUsuario, String emailUsuario, String usuario, String senhaUsuario, Boolean administradorUsuario) {
        this.idusuario = idUser;
        this.nomeUsuario = nomeUsuario;
        this.emailUsuario = emailUsuario;
        this.usuario = usuario;
        this.senhaUsuario = senhaUsuario;
        this.administradorUsuario = administradorUsuario;
        this.ativoUsuario = true;
    }

    public List<Usuario> getLista() {
        UsuarioDAO dao = new UsuarioDAO();
        List<Usuario> lista = dao.selectLista();
        return lista;
    }

    public List<Usuario> getListaByNome(String nome) {			
		UsuarioDAO dao        = new UsuarioDAO();
		List<Usuario> lista   = dao.selectListaByNome(nome);	
		return lista;
	}	
    
    public Usuario getById(int id) {
        UsuarioDAO dao = new UsuarioDAO();
        return dao.selectById(id);
    }

    public boolean remove(Usuario usuario) {
        UsuarioDAO dao = new UsuarioDAO();
        if (dao.delete(usuario)) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean alteraPermissao(Usuario usuario) {
        UsuarioDAO dao = new UsuarioDAO();
        if (dao.alterarPermissao(usuario)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @return the idusuario
     */
    public int getIdusuario() {
        return idusuario;
    }

    /**
     * @param prontuario the prontuario to set
     */
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

    public int getProntuario() {
        return prontuario;
    }

    /**
     * @param prontuario the prontuario to set
     */
    public void setProntuario(int prontuario) {
        this.prontuario = prontuario;
    }
    
    /**
     * @return the nomeUsuario
     */
    public String getNomeUsuario() {
        return nomeUsuario;
    }

    /**
     * @param nomeUsuario the nomeUsuario to set
     */
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    /**
     * @return the emailUsuario
     */
    public String getEmailUsuario() {
        return emailUsuario;
    }

    /**
     * @param emailUsuario the emailUsuario to set
     */
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }

    /**
     * @return the usuario
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * @return the senhaUsuario
     */
    public String getSenhaUsuario() {
        return senhaUsuario;
    }

    /**
     * @param senhaUsuario the senhaUsuario to set
     */
    public void setSenhaUsuario(String senhaUsuario) {
        this.senhaUsuario = senhaUsuario;
    }

    /**
     * @return the administradorUsuario
     */
    public Boolean getAdministradorUsuario() {
        return administradorUsuario;
    }

    /**
     * @param administradorUsuario the administradorUsuario to set
     */
    public void setAdministradorUsuario(Boolean administradorUsuario) {
        this.administradorUsuario = administradorUsuario;
    }

    /**
     * @return the prontuarios
     */
    public Set getProntuarios() {
        return prontuarios;
    }

    /**
     * @param prontuarios the prontuarios to set
     */
    public void setProntuarios(Set prontuarios) {
        this.prontuarios = prontuarios;
    }

    /**
     * @return the ativoUsuario
     */
    public Boolean getAtivoUsuario() {
        return ativoUsuario;
    }

    /**
     * @param ativoUsuario the ativoUsuario to set
     */
    public void setAtivoUsuario(Boolean ativoUsuario) {
        this.ativoUsuario = ativoUsuario;
    }

}
